### ISSUE TITLE
Most languages - Field papers needs updating

### ISSUE THREAD

**Issue by Nick-Tallguy** [Nick-Tallguy/Nick-Tallguy.github.io#19]
Document in mobile-mapping section of all languages except German & English is actually about (Portuguese section talks of walking papers with a different permalink) - needs updating.causes broken links & 404 errors.

Should we remove this altogether - walking papers is now so far out of date that this guide may not be useful.

Options  
-  add a comment at head of file that this section of LearnOSM is out of date and needs updating  
-  delete the file  
-  do nothing - not really an option

**Comment by Nick-Tallguy** [comment]
I've added a comment at the head of the file

    Caution - this section is known to be out of date - there is an current section at [English - field papers](/en/mobile-mapping/field-papers/) or [German](/de/mobile-mapping/field-papers/)

**Comment by Nick-Tallguy** [comment]
@michael63-osm I suggest I make this one of the first files to be translated on transifex. Would it be best to have the German or English version as the 'base' for this - I suspect most of our translators can cope with English to ?, but don't know how many would be able to deal with German to ?

**Comment by michael63-osm** [comment]
@Nick-Tallguy it really does not matter as the contents is identical. After having translated the document to German I made the same screenshots again using the English interface and made further necessary amendments to the English document so both are now synchronized.

**Comment by Nick-Tallguy** [comment]
On Transifex now. When translated problem is solved
