### ISSUE TITLE
Norwegian Translation

### ISSUE THREAD

**Issue by Nick-Tallguy** [Nick-Tallguy/Nick-Tallguy.github.io#20]
@andersar Thank you for your work so far in translating LearnOSM.  

I've recently setup a 'staging site' which allows us to try things out before passing them on to the main site. You can view this staging site here http://nick-tallguy.github.io/nb/

One of the things we are working on is re-arranging the site to make it easier for newcomers to find what they need. At the moment the staging site shows some of the proposed changes, and I am putting more in place so that when we pass it on to the normal site at http://learnosm.org/nb/. You can easily see that the staging site contains many of the translations you have prepared, while the main site does not (yet). As the staging site is not normally visible to anyone who does not know of its existence, it is an ideal place to try things out, and make sure they are perfect before passing them on to the main site.  We are in the process of moving many files out of the beginner section, into other sections - nothing is lost, but it will appear in a different section. We are also moving the main guide to editing with iD into the beginner section.

It will be a lot easier for us if you are working on the staging site to carry out your translations. I've placed into the _posts/nb/beginner/  a file for translating - 0200-12-23-id-editor.md and I've pasted into it a hidden section that contains the translating you have already done on the now deleted start id file.

---- to be continued.

**Comment by Nick-Tallguy** [comment]
@andersar sorry, I was called away, so you are getting this as two halves of a message. 

You have a fork of the staging site on [your homepage in github](https://github.com/andersar), where it appears like this  
![image](https://cloud.githubusercontent.com/assets/6763965/8060193/e3f4aee0-0ebb-11e5-93e8-bf3d6fbcf1ef.png)

Click on the heading of Nick-Tallguy.github.io & [your screen will show something that includes a view with this](https://github.com/andersar/Nick-Tallguy.github.io)  
![image](https://cloud.githubusercontent.com/assets/6763965/8060271/3b970120-0ebc-11e5-9a19-0a3614c4f9a8.png)

At the bottom of the screenshot above it reads **This branch is 59 commits behind Nick-Tallguy:master**  and to the right of this it says **Pull Request**.  
This means that I have made 59 changes to the main site, which you can't see on your version, until you click on the **Pull Request** icon, when you can then make your version up to date.

A summary would be - I can 'pull' from you but I can't 'push' to you - only you can make your version up to date.

Once you've done the pull request, your version will be up to date and you should be able to see the file 0200-12-23-id-editor. It would be great if you could translate this next. 

Once you have done some of the translating you can push it to the staging site, or I can pull it in, and you can see what it looks like. Only when you are fully happy will I get it across to the main site.  

Any problems, please get back to me.

And thank you for your work on this so far - it is appreciated. The site analyser shows that 39 different people have looked at the Norwegian section of the site so far in June 2015, so it is starting to be used.

Regards

Nick

**Comment by andersar** [comment]
Thanks @Nick-Tallguy , this seemed like a walk in the park. Until I actually tried it. As described, I can see I'm a little behind your current master, and I press Pull Request. But I'm getting the window displayed below instead. Any obvious errors I'm making here? 

![screenshot](https://cloud.githubusercontent.com/assets/11366760/8101645/7415460c-1019-11e5-9603-368e8525c5c5.JPG)

**Comment by Nick-Tallguy** [comment]
Hi Anders,

Click on the change Base link (from my phone so brief)

Nick
(OSM=Tallguy)

dodgy didgits as using a phone with a spell chequer.

Humanitarian OpenStreetMap Team Member

**Comment by andersar** [comment]
Thanks, that seemed to do the trick.

**Comment by Nick-Tallguy** [comment]
Hi @andersar I think you need to actually merge - On this view  
![image](https://cloud.githubusercontent.com/assets/6763965/8107400/c637ecd8-1040-11e5-8f3e-ec00847c42f4.png)
click on the "#1" bottom right, scroll to the bottom of the screen until you get something like this  
![image](https://cloud.githubusercontent.com/assets/6763965/8107432/0dcf0ca2-1041-11e5-8a7e-4e2f7b3d8e20.png)

but you will have an extra button allowing you to merge the changes. Click on the merge, and you will then have an up to date fork (I hope - I'm learning on this as well) If I've got this wrong, let me know so I can make sure I get the instructions right for the next person.

Thanks for persevering. 

Nick

**Comment by bgirardot** [comment]
Hi Nick, et. al.,



Does this help at all?

http://www.hpique.com/2013/09/updating-a-fork-directly-from-github/

Answer 2 to this question has some updated info on the process:

http://stackoverflow.com/questions/7244321/how-to-update-github-forked-repository

Cheers,
blake

**Comment by bgirardot** [comment]
I actually just tried this process, which is totally counter intuitive 
and makes no sense in light of what pull requests are supposed to be.

and it kind of worked, but I ended up 1 commit ahead of the repo I was 
trying to sync with as detailed and mentioned and unanswered in the 
stackover flow thread I linked to.

Nick, for fun if you could make a change to your 2 file test repo, I 
could see if it does in fact make any kind of difference going forward 
(I am sure it will, just because github)

cheers
blake

**Comment by bgirardot** [comment]
Just for fun, here is a 1.5 min long video of the process I just tried 
where it "sort of" worked but not really because I am not even, I am one 
commit ahead now.

https://youtu.be/WuBFEWuYDJk

cheers,
blake

**Comment by Nick-Tallguy** [comment]
@bgirardot I've updated https://github.com/Nick-Tallguy/Testing_learnosm with a very short commit - Good luck, I'd really like to see a nice short & easy way of passing this information on reliably.

Nick

**Comment by Nick-Tallguy** [comment]
Paste of comments from http://stackoverflow.com/questions/7244321/how-to-update-github-forked-repository  "203"

Here’s how to update your fork directly from GitHub (as shown in the video above):

+  Open your fork on GitHub.  
+  Click on Pull Requests.  
+  Click on New Pull Request. By default, GitHub will compare the original with your fork, and there shouldn’t be anything to compare if you didn’t make any changes.  
+  Click on switching the base (if no changes were made in the fork) or click Edit and switch the base manually. Now GitHub will compare your fork with the original, and you should see all the latest changes.  
+  Click on Create to create a pull request for this comparison and assign a predictable name to your pull request (e.g., Update from original).  
+  Click on Send pull request.  
+  Scroll down and click Merge pull request and finally Confirm merge. If your fork didn’t have any changes, you will be able to merge it automatically.  

The video at https://youtu.be/WuBFEWuYDJk is also very good

**Comment by bgirardot** [comment]
Nick, I am sorry to report that I am not sure this is going to classify 
as short and easy.

I am really really appalled at how non transparent this is.

So my next attempt at doing the pull request method, of course it tried 
to make a "regular" pull request to your repo for the 1 commit I was 
ahead of your repo after my last "sync".

Switching the pop down menus so the left side pointed my own repo 
eventually got the "compare across repos" link to appear, which then 
clicking did show the change you made.

I could go through the "pull request" process to get your changes into 
my fork, but now my fork is 2 commits ahead of your repo, instead of 1 
commit ahead.

it seems like every time one "syncs" (in quotes because it does not 
really sync) it puts my fork one more commit ahead.

ybon had a good suggestion to get around some of this:

someone who knows how to really do the traditional way of keeping a fork 
in sync should get admin priviledges on all the forks that contribute to 
the main learnosm repo and that one person would do the fork syncing the 
traditional way via a local clone and the command line for the contributor.

however, an even easier way is to have contributors really only work on 
one thing at time and after we merge their pull requests, they delete 
their fork and re-fork the now updated learnosm.

that is still not perfect, but might be the easiest thing.

**Comment by Nick-Tallguy** [comment]
We need to keep working on this  
>however, an even easier way is to have contributors really only work on 
one thing at time and after we merge their pull requests, they delete 
their fork and re-fork the now updated learnosm.

may not be the answer. It took me quite a while to work out how to delete a fork!

**Comment by Nick-Tallguy** [comment]
@bgirardot I've just created a file at https://github.com/Nick-Tallguy/Nick-Tallguy.github.io/blob/master/_posts/en/editing/draft-0300-01-01-testediting.md

You already have collaborator access to this site. Could you try editing the file online - either directly from the file manager, or using prose.io   

If we gave any translator 'collaborator' rights to this staging site, they can make changes & authorise them themselves. They are always working on an up-to-date repository. Yes, they could make mistakes, but that is no problem on the staging site, as long as we correct them before someone with 'owner' or 'collaborator' rights for the main LearnOSM site pushes those changes across.  A collaborator on this site is unlikely to have the accesses on the main site. I have 'owner' rights on this site and can roll-back any changes that are a real problem - as could anyone else with collaborator access who can work out what to do.

**Comment by Nick-Tallguy** [comment]
@bgirardot I can see your changes from  
![image](https://cloud.githubusercontent.com/assets/6763965/8111800/b670dd62-105b-11e5-9188-5cabbcbdd88a.png)

& when I pull using terminal to make sure I am up to date, it get   
![image](https://cloud.githubusercontent.com/assets/6763965/8111833/e4f7950e-105b-11e5-9a0c-ba66df536446.png)

so I think it gives me plenty of options to notice. I can view your changes easily, and can update them if you've accidentally formatted something in a strange way. 

For me it looks good, but how easy was it for you?

**Comment by bgirardot** [comment]
that method was easy. I will try it with the new branch method next.

**Comment by Nick-Tallguy** [comment]
@andersar we are currently testing using [Transifex](https://www.transifex.com/) as a method of providing translations for the site. It should be a lot simpler for the translators. LearnOSM is listed under the HOT section &, if you have the time, it would be great if you could help us there.

**Comment by andersar** [comment]
@Nick-Tallguy Excellent - I've already participated in the HOT Tasking Manager 2 translation there, but I thought there was some technical issue that made it simpler to translate LearnOSM here. Oh well, Transifex is very simple to work with. I'll have a look later!

**Comment by Nick-Tallguy** [comment]
@andersar very good progress on Transifex. Labels now all reading correctly - can be viewed at http://nick-tallguy.github.io/nb/ & will be pushed across to main LearnOSM site within the next couple of days.

**Comment by Nick-Tallguy** [comment]
Working with Transifex
