### ISSUE TITLE
Kiswahili ongoing translation

### ISSUE THREAD

**Issue by Nick-Tallguy** [Nick-Tallguy/Nick-Tallguy.github.io#24]
[This issue refers from the main LearnOSM issues list](https://github.com/hotosm/learnosm/issues/359)  

@kateregga1 I am proposing major changes to the layout of the site, and these are currently being tried out on our [new staging site here](http://nick-tallguy.github.io/en/beginner/).  

Rather than have to move things around after you have translated them, could you [please click on this link to the staging site on github](https://github.com/Nick-Tallguy/Nick-Tallguy.github.io), and then fork the site, and do your translations on the fork of the staging site. This also makes it easier for you to see how your translations will look, before we transfer them across to the main site.

I've already moved the files within the Kiswahili section of the staging site, so there shouldn't be any other changes for you, unless you request them because you are ready for more translations.

I am carrying out quite major changes to the sections & headings, so it will probably be at least a week, possibly 2 or 3 weeks before we are ready to transfer everything across, but I can always make an exception and transfer your translations earlier if needed.

Sorry for creating extra work for you, but I'm hoping it will make the site easier to navigate in the future.

Keep up the good work.

Regards

Nick

**Comment by Nick-Tallguy** [comment]
@kateregga1  we are currently testing using [Transifex](https://www.transifex.com/) as a method of providing translations for the site. It should be a lot simpler for the translators. LearnOSM is listed under the HOT section &, if you have the time, it would be great if you could help us there.

**Comment by kateregga1** [comment]
Thanks @Nick-Tallguy 

Let me try out Transifex and see how it works for me. Will keep you updated.

**Comment by kateregga1** [comment]
Currently Swahili is not listed among the available languages here https://www.transifex.com/projects/p/learnosm-1/

I have requested for it, will start on the translation once it is available. 
I think if its work flow is easier then it will help me get other people help out on the translation.

**Comment by Nick-Tallguy** [comment]
On 12/07/15 12:44, Geoffrey Kateregga wrote:
>
> Currently Swahili is not listed among the available languages here 
> https://www.transifex.com/projects/p/learnosm-1/
>
> I have requested for it, will start on the translation once it is 
> available.
> I think if its work flow is easier then it will help me get other 
> people help out on the translation.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Nick-Tallguy/Nick-Tallguy.github.io/issues/24#issuecomment-120710864>.
>
I've accepted the language, but it won't let me add you to the 
translators!  I'm sending a message to someone who may have the 'rights' 
to add you.

-- 

Nick

Volunteer 'Tallguy' for 
https://wiki.openstreetmap.org/wiki/Humanitarian_OSM_Team

http://www.openstreetmap.org/user/Tallguy

**Comment by kateregga1** [comment]
Thanks @Nick-Tallguy, I now have access to the Swahili page as a coordinator, do I have rights to add translators and reviewers. I have a group of 12 people who would like to help.

**Comment by Nick-Tallguy** [comment]
I've forwarded your message.  Not sure who will get back to you but that
sounds very good to me.

Nick
(OSM=Tallguy)

dodgy didgits as using a phone with a spell chequer.

Humanitarian OpenStreetMap Team Member

**Comment by kateregga1** [comment]
I am able to add translators now, have just sent out invitations, then I will be meeting them soon to take them through the process.

**Comment by Nick-Tallguy** [comment]
Ok.

Are you able to tell if my part of the process is okay?

Once I know that I am set up okay I will add more guides.

Nick
(OSM=Tallguy)

dodgy didgits as using a phone with a spell chequer.

Humanitarian OpenStreetMap Team Member

**Comment by Nick-Tallguy** [comment]
Closing as stale. Mainly using Transifex but other options considered
