### ISSUE TITLE
zh Simplified Chinese

### ISSUE THREAD

**Issue by Nick-Tallguy** [Nick-Tallguy/Nick-Tallguy.github.io#28]
https://github.com/hotosm/learnosm/issues/426 refers

Hi @qyu I have added you as a collaborator to our staging site - you're getting this message from it. We are starting to use this site as a stage or testing site, before transferring the information to the main site when we are happy with it.

I've started to set up the site with the files for Simplified Chinese - you can view it here http://nick-tallguy.github.io/en/  

I've placed into the folder [_posts/zh](https://github.com/Nick-Tallguy/Nick-Tallguy.github.io/tree/master/_posts/zh) the files to make the translation appear, and the files for what we are planning to be the beginners section (there are still meetings and decisions to be made, so the makeup of the beginners section may alter, but it is likely to include at least these files) I can add more files later when you are ready.

We also need the following text translated - if you provide the translation i will make sure it appears in the right place:
How do you want it to appear in the title bar eg..
'sw' Kiswahili
'uk' Українська
'zh' Simplified Chinese

Learn OpenStreetMap Step by Step
Help improve our guides
Are you a workshop organizer
Check out training material for this guide (in English)
Was this chapter helpful?
Let us know and help us improve the guides!
Get started

Any problems, please let me know & I'll do my best to sort it out. Let me know when you are happy that you've got the start at a point where I should transfer it onto the main site.

Thanks in anticipation & Good luck.

Nick

**Comment by qyu** [comment]
Hi Nick,
Thank you very much for adding me to the staging site. 'zh' for Simplified Chinese works. 
Learn OpenStreetMap Step by Step  步骤学习OpenStreetMap
Help improve our guides 帮助我们改善指南目录
Are you a workshop organizer 你是一个研讨会组织者么？
Check out training material for this guide (in English) 查看这份指南的培训资料 （英文）
Was this chapter helpful? 这个章节有帮助么？
Let us know and help us improve the guides! 给我们建议，来一起改善指南目录！
Get started 开始吧
I got the flu last week, my translation work may be slow down. I'll keep you update for the translation.Thanks again for the setup.
Cheers,Ching



Date: Tue, 16 Jun 2015 14:18:49 -0700

**Comment by Nick-Tallguy** [comment]
@qyu  we are currently testing using [Transifex](https://www.transifex.com/) as a method of providing translations for the site. It should be a lot simpler for the translators. LearnOSM is listed under the HOT section &, if you have the time, it would be great if you could help us there.

**Comment by qyu** [comment]
Awesome! Thank you for sharing this info. I'll try to use it to translate the LearnOSM. : ) Maptime Beijing is working on the growing OSM China community. We are in need of Chinese translation.

Date: Sun, 12 Jul 2015 04:14:18 -0700

**Comment by Nick-Tallguy** [comment]
Translation now on Transifex.
