### ISSUE TITLE
iD section of LearnOSM is duplicated in github wiki

### ISSUE THREAD

**Issue by Nick-Tallguy** [Nick-Tallguy/Nick-Tallguy.github.io#32]
Allocated to @Anwaario to review & reply

http://learnosm.org/en/beginner/id-editor/ contains instructions on how to use the iD editor.
https://github.com/hotosm/learnosm/wiki/iD-Editor also concerns the use of the iD editor.

Review the two guides, and make a note as a reply to this issue of anything in the github wiki article which should be added to the LearnOSM entry.

**Comment by Anwaario** [comment]
I will address each section by it's heading in the Wiki with the exception of the Introduction as it was changed to the heading iD Editor.  Besides this change the headings remain similar across the wiki and LearnOsm page.

_SAME_ = No Significant Differences
_LearnOSM site better_ = More information && better choices in structure, flow, and/or grammar.

**The iD Editor** - the only edit is a deletion of the word - "de-facto"
**Starting the iD Editor**  SAME
**iD Editor User Interface** SAME
**Configuring the Background Layer** SAME
**Basic Editing with iD** The word "Editor" was omitted after iD on the website.
**Adding Points** LearnOSM site better
**Drawing Lines** LearnOSM site better
**Drawing Shapes** LearnOSM site better
**Saving Your Changes** LearnOSM site better
**Additional Information and Custom Tags** LearnOSM site better
**iD versus JOSM** LearnOSM site better

**Comment by Nick-Tallguy** [comment]
@Anwaario thanks for your work on this - I've made significant changes to the wiki as a direct result of your & another persons-review - I  didn't realise he was also reviewing.  Closing this issue now.
