### ISSUE TITLE
rename nepal-disaster to disaster mapping

### ISSUE THREAD

**Issue by Nick-Tallguy** [Nick-Tallguy/Nick-Tallguy.github.io#35]
Yellow button currently labelled "HOT Disaster mapping" links to a single file called _posts/en/coordination/0500-10-27-nepal.md  which has been updated so that it is not so event specific. I would like that file renamed 0500-10-27-disaster_mapping.md, 
and it's permalink changed to /en/coordination/disaster-mapping
At the same time (or we will get 1000's of 404 errors) I need all of the files
_posts/bi/0100-01-01-index.md
_posts/de/0100-01-01-index.md
_posts/en/0100-01-01-index.md
etc. - one for each language on the site
updated so that this line interspanlink: /en/coordination/nepal-disaster  changes to   interspanlink: /en/coordination/disaster-mapping

**Comment by russdeffner** [comment]
I keep going back and forth on this; lot's of the information that will end up in this section will be relevant to more 'general' OSM coordination; i.e. local communities organizing projects, etc.  So now I'm leaning back towards naming it something not HOT specific, like 'Coordinating OSM Group Efforts' or something.  Just a thought.

**Comment by Nick-Tallguy** [comment]
How about **0500-10-27-aid_agency_mapping.md**

**Comment by Nick-Tallguy** [comment]
As a try out, I've set the staging site to **Humanitarian Mapping**  Remote Mapping Information, and renamed the file it points to as **humanitarian**.

Can be viewed at http://nick-tallguy.github.io/en/  

I see this as a possible stopgap pending either;

1. Moodle taking over, or
2. Possible redesign for the front page of LearnOSM

**Comment by Nick-Tallguy** [comment]
Has been renamed.
