### ISSUE TITLE
Move Remote, Armchair or Mapathon editing to beginner section

### ISSUE THREAD

**Issue by russdeffner** [Nick-Tallguy/Nick-Tallguy.github.io#38]
This is more a suggestion, but when looking at what is already in the coordination section and what I am working on for the Activation Curriculum, I think the module: http://learnosm.org/en/coordination/remote/ actually fits better elsewhere, maybe beginner or intermediate but it's not really about 'coordination' but 'participation'.

**Comment by michael63-osm** [comment]
I think that 0500-10-25-tasking-manager.md, 0500-10-20-remote.md and 0500-10-15-remote-tracing.md are closely related and together offer a sound introduction to what we understand by remote mapping. This is why I vote for moving these documents to a "remote" section of their own. One day we might incorporate more specific regional guides such as Blake's Western Africa mapping hints into this section.

The topics are too advanced for beginners and therefore do not fit into our new slim beginners' section where readers should become familiar with OSM in general and some basic editing techniques. We no longer have an intermediate section - much of that material is now part of the josm section which is already fairly large. And remote mapping is not restricted to josm users.

**Comment by Nick-Tallguy** [comment]
@michael63-osm I agree, but would like to wait a little to see developments, then propose changes & arrange them in one batch.

**Comment by Nick-Tallguy** [comment]
Closing now. We have the quick links button. Worth considering for the future though.
