### ISSUE TITLE
Liquid syntax error slowing site build

### ISSUE THREAD

**Issue by Nick-Tallguy** [Nick-Tallguy/Nick-Tallguy.github.io#76]
I've been experiencing problems building the site locally (used by me to make sure things are okay before uploading, but also as the method to generate the sitemap.xml). 

Commit rXRiQs3C4J is my attempt to fix this. I think everything is okay and working fine.

@michael63-osm  please can you check out my changes and when/if you are satisfied we will make the same changes on the main site.

**Comment by michael63-osm** [comment]
It seems that everything works fine on the staging site so feel free to transfer this change. I have no local setup on my computer but did not receive any error when GitHub built the pages so I assumed it was valid code. 

As far as omitting some dot in `site.translations.[page.lang]` is concerned - I took the code from http://jekyllrb.com/docs/variables/ where it looks like
 `site.categories.CATEGORY` - The list of all Posts in category CATEGORY. 

But obviously your code works fine

**Comment by Nick-Tallguy** [comment]
Thanks @michael63-osm - it was only because of the error messages I was receiving on the terminal when running the site locally. Both sites are now updated
